//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementApp.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchDeatil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BatchDeatil()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int BatchId { get; set; }
        public string BatchName { get; set; }
        public System.DateTime BatchStartDate { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<System.DateTime> SessionDate { get; set; }
        public string Instructorname { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual SessionDetail SessionDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
    }
}
