//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementApp.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finance
    {
        public int TransactionId { get; set; }
        public string TransactionType { get; set; }
        public Nullable<int> StudentId { get; set; }
        public decimal Amount { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string Comment { get; set; }
        public string PaidBy { get; set; }
        public string PaidTo { get; set; }
        public string TransactionMode { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
