//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementApp.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class MissedSession
    {
        public int MissedId { get; set; }
        public Nullable<int> MissedSessionId { get; set; }
        public Nullable<int> StudentId { get; set; }
    
        public virtual SessionDetail SessionDetail { get; set; }
        public virtual Student Student { get; set; }
    }
}
